name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: [self-hosted, M1]
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build
        env:
          # CSC_LINK: ${{ secrets.MACOS_CERT }}
          # CSC_KEY_PASSWORD: ${{ secrets.MACOS_CERT_PASS }}
          NOT_APPLE_ID: ${{ secrets.APPLE_ID }}
          NOT_APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
        run: |
          yarn install
          yarn run build-desktop

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          path: |
            packages/008desktop/build/008-desktop-win.exe
            packages/008desktop/build/008-desktop-mac.dmg
            packages/008desktop/build/008-desktop-linux.AppImage

  sign-win:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: bin

      - name: Sign win
        shell: bash
        run: |
          dotnet tool install --global AzureSignTool 
          AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v "bin/008-desktop-win.exe"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            bin/008-desktop*
