name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Upload agent008.ai
        timeout-minutes: 10
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOST: ${{ secrets.SITE_HOST }}
        run: |
          gh release download --repo kunzite-app/008 --pattern '008-desktop*' --dir bin

          mkdir -p ~/.ssh/
          echo "34.175.178.71" > ~/.ssh/known_hosts

          cat ~/.ssh/known_hosts

          echo "${{ secrets.SITE_SSH_KEY }}" > private.key 
          chmod 600 private.key

          scp -P ${{ secrets.SITE_PORT }} -i private.key -r bin ${{ secrets.SITE_USER }}@34.175.178.71:~/public
