name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Upload agent008.ai
        timeout-minutes: 10
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo kunzite-app/008 --pattern '008-desktop*' --dir bin

          ssh-keyscan -p ${{ secrets.SITE_PORT }} ${{ secrets.SITE_HOST }} >> ~/.ssh/known_hosts

          echo "${{ secrets.SITE_SSH_KEY }}" > 008.key 
          chmod 600 008.key

          scp -P ${{ secrets.SITE_PORT }} -i 008.key -r bin ${{ secrets.SITE_USER }}@${{ secrets.SITE_HOST }}:~/public
